--青空的巫女 Vichenta
function c10981016.initial_effect(c)
	aux.EnablePendulumAttribute(c) 
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_UPDATE_LSCALE)
	e1:SetRange(LOCATION_PZONE)
	e1:SetTargetRange(0,LOCATION_SZONE)
	e1:SetTarget(c10981016.ptarget)
	e1:SetValue(1)
	c:RegisterEffect(e1) 
	local e2=e1:Clone()
	e2:SetCode(EFFECT_UPDATE_RSCALE)
	c:RegisterEffect(e2)	
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_FIELD)
	e3:SetCode(EFFECT_UPDATE_LSCALE)
	e3:SetRange(LOCATION_MZONE)
	e3:SetTargetRange(LOCATION_SZONE,0)
	e3:SetTarget(c10981016.ptarget)
	e3:SetValue(1)
	c:RegisterEffect(e3) 
	local e4=e3:Clone()
	e4:SetCode(EFFECT_UPDATE_RSCALE)
	c:RegisterEffect(e4)   
end
function c10981016.ptarget(e,c)
	return c:IsFaceup() and c:GetSequence()==6 or c:GetSequence()==7
end
